baseURL = "https://blog.terryx.com/"
title = "欲說還休"
theme = "ink"
defaultContentLanguage = "zh-cn"
paginate = 10

copyright = "© 2016 - 2026 TerryX"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  subtitle = "TerryX's Blog"
  description = "TerryX's Blog"
  mode = "auto"
  featherIconsCDN = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "All posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 4

[[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/lele94218"

[[params.social]]
  name = "RSS"
  icon = "rss"
  url = "/index.xml"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
